name: Upload Data to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install DVC
        run: pip install dvc

      - name: Configure DVC
        run: dvc remote modify storage url azure://<CONTAINER_NAME> --public-key "$AZURE_STORAGE_ACCOUNT" --secret-key "$AZURE_STORAGE_ACCESS_KEY"

      - name: Fetch DVC data
        run: dvc pull

      - name: Upload data to Azure Blob Storage
        run: dvc push -r storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
