




#FROM puckel/docker-airflow:1.10.9
#RUN pip install psycopg2-binary

FROM puckel/docker-airflow:1.10.9

RUN pip install psycopg2-binary==2.8.6 --no-cache-dir



RUN pip install openai
RUN pip install requests
